### ISSUE TITLE
Position is not always calculated correctly

### ISSUE THREAD

**Issue by jazzthief81** [thewca/wca-workbook-assistant#93]
Sébastien posted a workbook for Hessen Open 2014 where the Workbook Assistant showed ranks 21 and 22 for 2 people in the position column when their ranks should have been tied at 21. Opening the workbook in Excel shows the correct ranks in the position column.

**Comment by jfly** [comment]
Hey @SAuroux, is this still an issue?

**Comment by SAuroux** [comment]
I have no idea, sorry.

**Comment by jfly** [comment]
Ok, since it doesn't seem to have been an issue, I'm going to optimistically close this issue =)
